#!/usr/bin/env bash
# Generate deploy/analytics/.env with fresh random secrets for the docker compose stack.
#
# Usage: deploy/analytics/scripts/gen-analytics-env.sh [--force] [OUTPUT]
#   OUTPUT   file to write (default: deploy/analytics/.env), created with mode 600
#   --force  overwrite an existing file. Postgres roles and the Garage key are created from
#            these values on FIRST start and persist in volumes: after rotating them you must
#            also run `docker compose down -v`, which DELETES ALL DATA.
# Passwords are [A-Za-z0-9] only (they are spliced into Postgres URLs). The Garage key id is
# `GK` + 24 hex and its secret 64 hex, the only formats Garage accepts.
set -euo pipefail
HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
FORCE=0
OUT=""
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    -h|--help) sed -n '2,10p' "${BASH_SOURCE[0]}"; exit 0 ;;
    -*) echo "gen-analytics-env: unknown option $arg" >&2; exit 2 ;;
    *) OUT=$arg ;;
  esac
done
OUT=${OUT:-$HERE/../.env}
command -v openssl >/dev/null || { echo "gen-analytics-env: openssl is required" >&2; exit 1; }
if [ -e "$OUT" ] && [ "$FORCE" != 1 ]; then
  echo "gen-analytics-env: $OUT exists; pass --force to overwrite (see --help)" >&2
  exit 1
fi
hex() { openssl rand -hex "$1"; }
alnum() { LC_ALL=C openssl rand -base64 96 | tr -dc 'A-Za-z0-9' | cut -c1-"$1"; }
# gen NAME KIND LEN PREFIX: generate into a variable (so a failing openssl aborts here, which a
# $(...) inside a heredoc would not) and validate exact length/format before using it.
gen() {
  local v re
  if [ "$2" = hex ]; then v=$(hex "$3") || exit 1; re="^[0-9a-f]{$(( $3 * 2 ))}$"
  else v=$(alnum "$3") || exit 1; re="^[A-Za-z0-9]{$3}$"; fi
  [[ $v =~ $re ]] || { echo "gen-analytics-env: failed to generate a valid value for $1" >&2; exit 1; }
  printf '%s' "$v"
}
S3_ACCESS_KEY=GK$(gen S3_ACCESS_KEY hex 12) || exit 1
S3_SECRET_KEY=$(gen S3_SECRET_KEY hex 32) || exit 1
GARAGE_RPC_SECRET=$(gen GARAGE_RPC_SECRET hex 32) || exit 1
GARAGE_ADMIN_TOKEN=$(gen GARAGE_ADMIN_TOKEN alnum 40) || exit 1
POSTGRES_PASSWORD=$(gen POSTGRES_PASSWORD alnum 32) || exit 1
LAKEKEEPER_DB_PASSWORD=$(gen LAKEKEEPER_DB_PASSWORD alnum 32) || exit 1
LAKEKEEPER_ENCRYPTION_KEY=$(gen LAKEKEEPER_ENCRYPTION_KEY alnum 48) || exit 1
TRINO_ADMIN_PASSWORD=$(gen TRINO_ADMIN_PASSWORD alnum 32) || exit 1
TRINO_METABASE_PASSWORD=$(gen TRINO_METABASE_PASSWORD alnum 32) || exit 1
TRINO_SHARED_SECRET=$(gen TRINO_SHARED_SECRET alnum 48) || exit 1
METABASE_DB_PASSWORD=$(gen METABASE_DB_PASSWORD alnum 32) || exit 1
METABASE_ENCRYPTION_KEY=$(gen METABASE_ENCRYPTION_KEY alnum 48) || exit 1
METABASE_ADMIN_PASSWORD=$(gen METABASE_ADMIN_PASSWORD alnum 32) || exit 1
HEC_TOKEN=$(gen HEC_TOKEN alnum 40) || exit 1
OTLP_BEARER_TOKEN=$(gen OTLP_BEARER_TOKEN alnum 40) || exit 1
# Write to a private temp file beside OUT and rename only on success, so a failure never
# destroys an existing .env (its secrets back persisted Postgres/Garage volumes).
umask 077
TMP=$(mktemp "$OUT.XXXXXX")
trap 'rm -f "$TMP"' EXIT
cat >"$TMP" <<ENV
# Generated by scripts/gen-analytics-env.sh. Keep private; do not commit.
S3_ACCESS_KEY=$S3_ACCESS_KEY
S3_SECRET_KEY=$S3_SECRET_KEY
GARAGE_RPC_SECRET=$GARAGE_RPC_SECRET
GARAGE_ADMIN_TOKEN=$GARAGE_ADMIN_TOKEN
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
LAKEKEEPER_DB_PASSWORD=$LAKEKEEPER_DB_PASSWORD
LAKEKEEPER_ENCRYPTION_KEY=$LAKEKEEPER_ENCRYPTION_KEY
TRINO_ADMIN_PASSWORD=$TRINO_ADMIN_PASSWORD
TRINO_METABASE_PASSWORD=$TRINO_METABASE_PASSWORD
TRINO_SHARED_SECRET=$TRINO_SHARED_SECRET
METABASE_DB_PASSWORD=$METABASE_DB_PASSWORD
METABASE_ENCRYPTION_KEY=$METABASE_ENCRYPTION_KEY
METABASE_ADMIN_PASSWORD=$METABASE_ADMIN_PASSWORD
HEC_TOKEN=$HEC_TOKEN
OTLP_BEARER_TOKEN=$OTLP_BEARER_TOKEN
ENV
mv -f "$TMP" "$OUT"
trap - EXIT
echo "gen-analytics-env: wrote $OUT" >&2
