#!/usr/bin/env bash
# Generate deploy/analytics/.env with fresh random secrets for the docker compose stack.
#
# Usage: deploy/analytics/scripts/gen-analytics-env.sh [--force] [OUTPUT]
#   OUTPUT   file to write (default: deploy/analytics/.env), created with mode 600
#   --force  overwrite an existing file. Postgres roles and the Garage key are created from
#            these values on FIRST start and persist in volumes: after rotating them you must
#            also run `docker compose down -v`, which DELETES ALL DATA.
# Passwords are [A-Za-z0-9] only (they are spliced into Postgres URLs). The Garage key id is
# `GK` + 24 hex and its secret 64 hex, the only formats Garage accepts.
set -euo pipefail
HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
FORCE=0
OUT=""
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    -h|--help) sed -n '2,10p' "${BASH_SOURCE[0]}"; exit 0 ;;
    -*) echo "gen-analytics-env: unknown option $arg" >&2; exit 2 ;;
    *) OUT=$arg ;;
  esac
done
OUT=${OUT:-$HERE/../.env}
command -v openssl >/dev/null || { echo "gen-analytics-env: openssl is required" >&2; exit 1; }
if [ -e "$OUT" ] && [ "$FORCE" != 1 ]; then
  echo "gen-analytics-env: $OUT exists; pass --force to overwrite (see --help)" >&2
  exit 1
fi
hex() { openssl rand -hex "$1"; }
alnum() { LC_ALL=C openssl rand -base64 96 | tr -dc 'A-Za-z0-9' | cut -c1-"$1"; }
rm -f "$OUT"
umask 077
cat >"$OUT" <<ENV
# Generated by scripts/gen-analytics-env.sh. Keep private; do not commit.
S3_ACCESS_KEY=GK$(hex 12)
S3_SECRET_KEY=$(hex 32)
GARAGE_RPC_SECRET=$(hex 32)
GARAGE_ADMIN_TOKEN=$(alnum 40)
POSTGRES_PASSWORD=$(alnum 32)
LAKEKEEPER_DB_PASSWORD=$(alnum 32)
LAKEKEEPER_ENCRYPTION_KEY=$(alnum 48)
HUE_DB_PASSWORD=$(alnum 32)
HUE_SECRET_KEY=$(alnum 48)
ENV
echo "gen-analytics-env: wrote $OUT" >&2
