//! End-to-end test: real sFlow UDP listener -> real production `/metrics`
//! HTTP endpoint, for the `loadgen sflow-udp` subcommand
//! (`tools/loadgen/src/sflow_udp.rs`).
//!
//! `tools/loadgen`'s own tests prove its generated bytes decode correctly
//! against `logthing::sflow::decoder::decode_datagram` directly (the
//! strongest, most direct check). This test instead proves the other half:
//! that a real sFlow v5 datagram sent over a real UDP socket reaches the
//! real `SflowListener` wiring (`SflowListener::start_with_shutdown`, the
//! same entry point `main.rs` uses) and that `sflow_datagrams_received`
//! actually increments on the real `/metrics` endpoint -- the exact counter
//! the task's manual smoke run also checks. Mirrors the shape of
//! `tests/ipfix_socket_drop_metric_e2e.rs` / `tests/zeek_received_metric_e2e.rs`.
//!
//! The datagram bytes below are a minimal, independently hand-built sFlow
//! v5 datagram (one flow_sample carrying one sampled_ipv4 record) -- NOT
//! imported from `tools/loadgen`, deliberately: this test's job is to prove
//! the listener/metrics wiring for *any* valid sFlow v5 datagram, not to
//! re-run `loadgen`'s own byte-for-byte round-trip proof a second time.
//!
//! This MUST be the only `#[tokio::test]` in this binary: `Server::run`
//! installs the Prometheus recorder via `metrics::set_global_recorder`,
//! which panics if called twice in one process. Cargo runs each
//! integration-test *file* as its own process, so keeping this file to a
//! single test keeps that call singular.

use logthing::config::{Config, MetricsConfig, TlsConfig};
use logthing::forwarding::flush_registry::FlushIntervalRegistry;
use logthing::server::Server;
use logthing::sflow::listener::{DefaultSflowHandler, SflowListener, SflowListenerConfig};
use logthing::stats::{SourceHourlyStats, ThroughputStats};
use std::sync::Arc;
use std::time::Duration;
use tokio::net::UdpSocket;
use tokio::sync::RwLock;

/// Reserve an ephemeral port: bind a probe socket, read the assigned port,
/// then drop the probe. Same TOCTOU-avoidance idiom as
/// `tests/ipfix_socket_drop_metric_e2e.rs`.
async fn reserve_udp_port() -> u16 {
    let probe = UdpSocket::bind("127.0.0.1:0").await.unwrap();
    probe.local_addr().unwrap().port()
}

async fn reserve_tcp_port() -> u16 {
    let probe = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    probe.local_addr().unwrap().port()
}

/// Build one minimal, valid sFlow v5 datagram: header + one flow_sample
/// carrying one sampled_ipv4 flow record. Byte-for-byte the same layout as
/// `FIXTURE_SFLOW_SAMPLED_IPV4` in `src/sflow/decoder.rs`, with source
/// address varied by `n` so N sends are N distinct datagrams.
fn build_sflow_datagram(n: u32) -> Vec<u8> {
    let mut buf = Vec::with_capacity(80);

    // Datagram header (28 bytes).
    buf.extend_from_slice(&5u32.to_be_bytes()); // version = 5
    buf.extend_from_slice(&1u32.to_be_bytes()); // agent_addr_type = 1 (IPv4)
    buf.extend_from_slice(&[10, 0, 0, 1]); // agent_addr
    buf.extend_from_slice(&0u32.to_be_bytes()); // sub_agent_id
    buf.extend_from_slice(&n.to_be_bytes()); // sequence_number
    buf.extend_from_slice(&n.to_be_bytes()); // uptime_ms
    buf.extend_from_slice(&1u32.to_be_bytes()); // num_samples = 1

    // flow_sample (data_format = 1), sample_length = 72.
    buf.extend_from_slice(&1u32.to_be_bytes());
    buf.extend_from_slice(&72u32.to_be_bytes());

    // flow_sample body header (32 bytes).
    buf.extend_from_slice(&n.to_be_bytes()); // sequence_number
    buf.extend_from_slice(&1u32.to_be_bytes()); // source_id
    buf.extend_from_slice(&1000u32.to_be_bytes()); // sampling_rate
    buf.extend_from_slice(&1000u32.to_be_bytes()); // sample_pool
    buf.extend_from_slice(&0u32.to_be_bytes()); // drops
    buf.extend_from_slice(&1u32.to_be_bytes()); // input_ifindex
    buf.extend_from_slice(&2u32.to_be_bytes()); // output_ifindex
    buf.extend_from_slice(&1u32.to_be_bytes()); // num_flow_records = 1

    // flow record: sampled_ipv4 (format 3), 32-byte body.
    buf.extend_from_slice(&3u32.to_be_bytes());
    buf.extend_from_slice(&32u32.to_be_bytes());
    buf.extend_from_slice(&60u32.to_be_bytes()); // original packet length
    buf.extend_from_slice(&6u32.to_be_bytes()); // protocol = TCP
    buf.extend_from_slice(&[172, 16, (n >> 8) as u8, n as u8]); // src_ip, varied by n
    buf.extend_from_slice(&[8, 8, 8, 8]); // dst_ip
    buf.extend_from_slice(&12345u32.to_be_bytes()); // src_port
    buf.extend_from_slice(&443u32.to_be_bytes()); // dst_port
    buf.extend_from_slice(&0u32.to_be_bytes()); // tcp_flags
    buf.extend_from_slice(&0u32.to_be_bytes()); // tos

    buf
}

#[tokio::test]
async fn sflow_datagrams_received_increments_on_real_metrics_endpoint() {
    let http_port = reserve_tcp_port().await;
    let metrics_port = reserve_tcp_port().await;
    let sflow_port = reserve_udp_port().await;

    // --- Real Server, with the real /metrics endpoint enabled ---
    let config = Config {
        bind_address: format!("127.0.0.1:{http_port}").parse().unwrap(),
        tls: TlsConfig {
            enabled: false,
            ..TlsConfig::default()
        },
        metrics: MetricsConfig {
            enabled: true,
            port: metrics_port,
        },
        ..Config::default()
    };

    let shared_config = Arc::new(RwLock::new(config.clone()));
    let server = Server::new(
        config,
        shared_config,
        Arc::new(ThroughputStats::new()),
        Arc::new(SourceHourlyStats::new()),
        FlushIntervalRegistry::new(),
    )
    .await
    .expect("Server::new must succeed with no S3/local targets configured");

    let (server_shutdown_tx, server_shutdown_rx) = tokio::sync::watch::channel(false);
    let server_task = tokio::spawn(async move {
        server
            .run(server_shutdown_rx)
            .await
            .expect("server run must not error");
    });

    // --- Real SflowListener, real production entry point ---
    let sflow_config = SflowListenerConfig {
        udp_port: sflow_port,
        bind_address: "127.0.0.1".to_string(),
        ..SflowListenerConfig::default()
    };
    let sflow_listener = SflowListener::new(sflow_config, Arc::new(DefaultSflowHandler));
    let (sflow_shutdown_tx, sflow_shutdown_rx) = tokio::sync::watch::channel(false);
    let sflow_task = tokio::spawn(async move {
        sflow_listener
            .start_with_shutdown(sflow_shutdown_rx)
            .await
            .expect("sflow listener run must not error");
    });

    // Give the listener time to bind.
    tokio::time::sleep(Duration::from_millis(300)).await;

    // --- Send 5 real sFlow v5 datagrams over a real UDP socket ---
    const DATAGRAM_COUNT: u32 = 5;
    let sender = UdpSocket::bind("127.0.0.1:0").await.unwrap();
    sender
        .connect(format!("127.0.0.1:{sflow_port}"))
        .await
        .unwrap();
    for n in 0..DATAGRAM_COUNT {
        sender.send(&build_sflow_datagram(n)).await.unwrap();
    }

    // --- Scrape the real /metrics endpoint over real HTTP until the counter appears ---
    let metrics_url = format!("http://127.0.0.1:{metrics_port}/metrics");
    let mut body = String::new();
    let deadline = tokio::time::Instant::now() + Duration::from_secs(10);
    loop {
        if let Ok(resp) = reqwest::get(&metrics_url).await
            && let Ok(text) = resp.text().await
            && text.contains("sflow_datagrams_received")
        {
            body = text;
            break;
        }
        if tokio::time::Instant::now() >= deadline {
            break;
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }

    assert!(
        body.contains("sflow_datagrams_received"),
        "regression: sflow_datagrams_received never appeared on the real \
         /metrics endpoint within the deadline. Full scrape body:\n{body}"
    );
    let count_line = body
        .lines()
        .find(|l| l.starts_with("sflow_datagrams_received"))
        .expect("counter line must be present");
    let count: f64 = count_line
        .split_whitespace()
        .last()
        .and_then(|v| v.parse().ok())
        .expect("counter value must parse as a number");
    assert_eq!(
        count, DATAGRAM_COUNT as f64,
        "expected sflow_datagrams_received == {DATAGRAM_COUNT} after sending \
         {DATAGRAM_COUNT} real datagrams; full scrape line: {count_line}"
    );

    // --- Clean shutdown ---
    sflow_shutdown_tx
        .send(true)
        .expect("sflow shutdown signal must send");
    tokio::time::timeout(Duration::from_secs(5), sflow_task)
        .await
        .expect("sflow listener task must join after shutdown")
        .expect("sflow listener task must not panic");

    server_shutdown_tx
        .send(true)
        .expect("server shutdown signal must send");
    tokio::time::timeout(Duration::from_secs(5), server_task)
        .await
        .expect("server task must join after shutdown")
        .expect("server task must not panic");
}
