{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "la.fullname" . }}-credentials
  labels: {{- include "la.labels" . | nindent 4 }}
type: Opaque
stringData:
  garage-rpc-secret: {{ .Values.credentials.garageRpcSecret | quote }}
  garage-admin-token: {{ .Values.credentials.garageAdminToken | quote }}
  s3-access-key: {{ .Values.credentials.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.credentials.s3SecretKey | quote }}
  postgres-password: {{ .Values.credentials.postgresPassword | quote }}
  lakekeeper-db-password: {{ .Values.credentials.lakekeeperDbPassword | quote }}
  lakekeeper-encryption-key: {{ .Values.credentials.lakekeeperEncryptionKey | quote }}
  hue-db-password: {{ .Values.credentials.hueDbPassword | quote }}
  hue-secret-key: {{ .Values.credentials.hueSecretKey | quote }}
{{- end }}
